
package cis104mmachineproject;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;


public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        NameTextField = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        CivilStatusLabel = new javax.swing.JLabel();
        DependentButton0 = new javax.swing.JRadioButton();
        CivilStatusButtonNo = new javax.swing.JRadioButton();
        IncomeLabel = new javax.swing.JLabel();
        CivilStatusButtonYes = new javax.swing.JRadioButton();
        DependentButton1 = new javax.swing.JRadioButton();
        DependentButton2 = new javax.swing.JRadioButton();
        DependentButton3 = new javax.swing.JRadioButton();
        DependentButton4 = new javax.swing.JRadioButton();
        DependentsLabel = new javax.swing.JLabel();
        IncomeTextField = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        NameDisplay = new javax.swing.JLabel();
        EmploymentStatusLabel = new javax.swing.JLabel();
        SelfEmployedButton = new javax.swing.JRadioButton();
        EmployedButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        MainLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        OldTaxLabel = new javax.swing.JLabel();
        TrainLawLabel = new javax.swing.JLabel();
        AnnualTaxDueLabel = new javax.swing.JLabel();
        MonthlyTaxDueLabel = new javax.swing.JLabel();
        TaxSavingsLabel = new javax.swing.JLabel();
        TakeHomePayLabel = new javax.swing.JLabel();
        AnnualTaxLabel1 = new javax.swing.JLabel();
        NewATIShowDisplay = new javax.swing.JLabel();
        OldATIShowDisplay = new javax.swing.JLabel();
        OldMTDShowDisplay = new javax.swing.JLabel();
        NewATDShowDisplay = new javax.swing.JLabel();
        OldTHPShowDisplay = new javax.swing.JLabel();
        OldATDShowDisplay = new javax.swing.JLabel();
        NewMTDShowDisplay = new javax.swing.JLabel();
        TaxSavingsShowDisplay = new javax.swing.JLabel();
        NewTHPShowDisplay = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ContributionsLabel = new javax.swing.JLabel();
        SSSContributionLabel = new javax.swing.JLabel();
        PAGIBIGContributionLabel = new javax.swing.JLabel();
        PhilHealthContributionLabel = new javax.swing.JLabel();
        TotalContributionsLabel = new javax.swing.JLabel();
        PhilHealthShowDisplay = new javax.swing.JLabel();
        SSSShowDisplay = new javax.swing.JLabel();
        TotalContributionShowDisplay = new javax.swing.JLabel();
        PAGIBIGShowDisplay = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        NameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        NameLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("  Name");
        NameLabel.setToolTipText("");
        NameLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CivilStatusLabel.setBackground(new java.awt.Color(255, 255, 255));
        CivilStatusLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CivilStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        CivilStatusLabel.setText("  Are you Married?");
        CivilStatusLabel.setToolTipText("");
        CivilStatusLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(DependentButton0);
        DependentButton0.setSelected(true);
        DependentButton0.setText("0");
        DependentButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependentButton0ActionPerformed(evt);
            }
        });

        buttonGroup2.add(CivilStatusButtonNo);
        CivilStatusButtonNo.setSelected(true);
        CivilStatusButtonNo.setText("No");
        CivilStatusButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CivilStatusButtonNoActionPerformed(evt);
            }
        });

        IncomeLabel.setBackground(new java.awt.Color(255, 255, 255));
        IncomeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        IncomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        IncomeLabel.setText("               Monthly Gross Income(in Php)");
        IncomeLabel.setToolTipText("");
        IncomeLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup2.add(CivilStatusButtonYes);
        CivilStatusButtonYes.setText("Yes");
        CivilStatusButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CivilStatusButtonYesActionPerformed(evt);
            }
        });

        buttonGroup1.add(DependentButton1);
        DependentButton1.setText("1");
        DependentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependentButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(DependentButton2);
        DependentButton2.setText("2");
        DependentButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependentButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(DependentButton3);
        DependentButton3.setText("3");
        DependentButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependentButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(DependentButton4);
        DependentButton4.setText("4");
        DependentButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DependentButton4ActionPerformed(evt);
            }
        });

        DependentsLabel.setBackground(new java.awt.Color(255, 255, 255));
        DependentsLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DependentsLabel.setForeground(new java.awt.Color(255, 255, 255));
        DependentsLabel.setText("     How many dependents do you have?");
        DependentsLabel.setToolTipText("");
        DependentsLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        IncomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomeTextFieldActionPerformed(evt);
            }
        });

        CalculateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CalculateButton.setText("CALCULATE");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        NameDisplay.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        NameDisplay.setForeground(new java.awt.Color(51, 51, 51));

        EmploymentStatusLabel.setBackground(new java.awt.Color(255, 255, 255));
        EmploymentStatusLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EmploymentStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmploymentStatusLabel.setText("     What is your Employment Status?");
        EmploymentStatusLabel.setToolTipText("");
        EmploymentStatusLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup3.add(SelfEmployedButton);
        SelfEmployedButton.setText("Self-Employed");
        SelfEmployedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelfEmployedButtonActionPerformed(evt);
            }
        });

        buttonGroup3.add(EmployedButton);
        EmployedButton.setSelected(true);
        EmployedButton.setText("Employed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(ResetButton)
                        .addGap(44, 44, 44)
                        .addComponent(ExitButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(DependentButton0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DependentButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DependentButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DependentButton3)
                        .addGap(18, 18, 18)
                        .addComponent(DependentButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(CivilStatusButtonYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CivilStatusButtonNo)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(EmployedButton)
                                .addGap(48, 48, 48)
                                .addComponent(SelfEmployedButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(IncomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DependentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmploymentStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CivilStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IncomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(NameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CivilStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CivilStatusButtonYes)
                    .addComponent(CivilStatusButtonNo))
                .addGap(28, 28, 28)
                .addComponent(DependentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DependentButton0)
                    .addComponent(DependentButton1)
                    .addComponent(DependentButton2)
                    .addComponent(DependentButton3)
                    .addComponent(DependentButton4))
                .addGap(34, 34, 34)
                .addComponent(EmploymentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelfEmployedButton)
                    .addComponent(EmployedButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(IncomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IncomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CalculateButton)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetButton)
                    .addComponent(ExitButton))
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        MainLabel.setFont(new java.awt.Font("Bahnschrift", 1, 28)); // NOI18N
        MainLabel.setForeground(new java.awt.Color(51, 51, 51));
        MainLabel.setText("      INCOME TAX CALCULATOR / TAKE-HOME PAY ESTIMATOR");
        MainLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(MainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        OldTaxLabel.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        OldTaxLabel.setForeground(new java.awt.Color(153, 153, 153));
        OldTaxLabel.setText("      OLD TAX Law");
        OldTaxLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        TrainLawLabel.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        TrainLawLabel.setForeground(new java.awt.Color(153, 153, 153));
        TrainLawLabel.setText("        TRAIN Law");
        TrainLawLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        AnnualTaxDueLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        AnnualTaxDueLabel.setText("  Annual Tax Due");
        AnnualTaxDueLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        MonthlyTaxDueLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        MonthlyTaxDueLabel.setText("  Monthly Tax Due");
        MonthlyTaxDueLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        TaxSavingsLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        TaxSavingsLabel.setText("  Tax Savings (OLD less TRAIN)");
        TaxSavingsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        TakeHomePayLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        TakeHomePayLabel.setText("  Monthly Take Home Pay");
        TakeHomePayLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        AnnualTaxLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        AnnualTaxLabel1.setText("  Annual Taxable Income");
        AnnualTaxLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        NewATIShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewATIShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        OldATIShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OldATIShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        OldMTDShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OldMTDShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        NewATDShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewATDShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        OldTHPShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OldTHPShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        OldATDShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OldATDShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        NewMTDShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewMTDShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        TaxSavingsShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        TaxSavingsShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        NewTHPShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NewTHPShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AnnualTaxDueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnnualTaxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthlyTaxDueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TakeHomePayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OldMTDShowDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OldATIShowDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(OldATDShowDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(OldTaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(OldTHPShowDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrainLawLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(NewATDShowDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewATIShowDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewMTDShowDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewTHPShowDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(TaxSavingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(TaxSavingsShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OldTaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrainLawLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnnualTaxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewATIShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OldATIShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnnualTaxDueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OldATDShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MonthlyTaxDueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OldMTDShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(NewATDShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewMTDShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TakeHomePayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OldTHPShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewTHPShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TaxSavingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TaxSavingsShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        ContributionsLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        ContributionsLabel.setForeground(new java.awt.Color(51, 51, 51));
        ContributionsLabel.setText("           CONTRIBUTIONS");
        ContributionsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        SSSContributionLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        SSSContributionLabel.setForeground(new java.awt.Color(51, 51, 51));
        SSSContributionLabel.setText("             SSS");
        SSSContributionLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        PAGIBIGContributionLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        PAGIBIGContributionLabel.setForeground(new java.awt.Color(51, 51, 51));
        PAGIBIGContributionLabel.setText("           PAGIBIG");
        PAGIBIGContributionLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        PhilHealthContributionLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        PhilHealthContributionLabel.setForeground(new java.awt.Color(51, 51, 51));
        PhilHealthContributionLabel.setText("         PhilHealth");
        PhilHealthContributionLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        TotalContributionsLabel.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        TotalContributionsLabel.setForeground(new java.awt.Color(51, 51, 51));
        TotalContributionsLabel.setText("        TOTAL CONTRIBUTIONS");
        TotalContributionsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        PhilHealthShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PhilHealthShowDisplay.setForeground(new java.awt.Color(51, 51, 51));
        PhilHealthShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        SSSShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SSSShowDisplay.setForeground(new java.awt.Color(51, 51, 51));
        SSSShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        TotalContributionShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalContributionShowDisplay.setForeground(new java.awt.Color(51, 51, 51));
        TotalContributionShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        PAGIBIGShowDisplay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PAGIBIGShowDisplay.setForeground(new java.awt.Color(51, 51, 51));
        PAGIBIGShowDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(PAGIBIGContributionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(PAGIBIGShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(PhilHealthContributionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PhilHealthShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(SSSContributionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SSSShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(ContributionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(TotalContributionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(TotalContributionShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(ContributionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SSSContributionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SSSShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PhilHealthContributionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhilHealthShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PAGIBIGContributionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PAGIBIGShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(TotalContributionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TotalContributionShowDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void DependentButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependentButton0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DependentButton0ActionPerformed

    private void CivilStatusButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CivilStatusButtonNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CivilStatusButtonNoActionPerformed

    private void CivilStatusButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CivilStatusButtonYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CivilStatusButtonYesActionPerformed

    private void DependentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependentButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DependentButton1ActionPerformed

    private void DependentButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependentButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DependentButton2ActionPerformed

    private void DependentButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependentButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DependentButton3ActionPerformed

    private void DependentButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DependentButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DependentButton4ActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        this.NameDisplay.setText("");
        this.OldATIShowDisplay.setText("");
        this.NewATIShowDisplay.setText("");
        this.OldATDShowDisplay.setText("");
        this.NewATDShowDisplay.setText("");
        this.OldMTDShowDisplay.setText("");
        this.NewMTDShowDisplay.setText("");
        this.OldTHPShowDisplay.setText("");
        this.NewTHPShowDisplay.setText("");
        this.TaxSavingsShowDisplay.setText("");
        this.SSSShowDisplay.setText("");
        this.PhilHealthShowDisplay.setText("");
        this.PAGIBIGShowDisplay.setText("");
        this.TotalContributionShowDisplay.setText("");
        this.NameTextField.setText("");
        this.IncomeTextField.setText("");
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        
        try {

        // Getting name input from user     
        String name = this.NameTextField.getText();
   
        // Getting monthly income input from user (Will cause error if No Input)
        
        double income = 0;

        income = Double.parseDouble(
            this.IncomeTextField.getText()
        );

        // Getting user's number of dependents input
        int dependent = 0; 
        if (DependentButton0.isSelected())
            dependent = 0;
        else if (DependentButton1.isSelected())
            dependent = 1;
        else if (DependentButton2.isSelected())
            dependent = 2;
        else if (DependentButton3.isSelected())
            dependent = 3;
        else if (DependentButton4.isSelected())
            dependent = 4;
        
        
        // Getting user's civil status input
        boolean civilStatus = true;
        if (CivilStatusButtonYes.isSelected())
            civilStatus = true;
        else if (CivilStatusButtonNo.isSelected())
            civilStatus = false;
        
        String userStatus = "e";
        if (EmployedButton.isSelected())
            userStatus = "e";
        else if (SelfEmployedButton.isSelected())
            userStatus = "se";
    
        // Creates new instance of IncomeTaxCalculator class
        IncomeTaxCalculator user1 = new IncomeTaxCalculator(name,income,dependent,civilStatus,userStatus);
    
    
        // Limiting decimal places for double and float data types and converting
        // result to String for display in Labels
        DecimalFormat df = new DecimalFormat("#,##0.00"); // 2 decimal places with comma separators for thousands place
    
        // Variable holders for tax calculation fields to be displayed
        double exemption1 = user1.getDependentExemption();
        double exemption2 = user1.getMarriedExemption();
        double annualIncome = user1.calculateAnnualIncomeOld();
        double annualTaxableIncomeNew = user1.calculateAnnualIncomeNew();
        
        // Old Annual Taxable Income returns zero when result is less than zero
        double annualTaxableIncomeOld = 0;
        double qualifier = annualIncome - (exemption1 + exemption2);
        if (qualifier >= 0)
            annualTaxableIncomeOld = qualifier;
        else
            annualTaxableIncomeOld = 0;
        
        
        double benefit1 = user1.getSSSDeduction();
        double benefit2 = user1.getPAGIBIGDeduction();
        double benefit3 = user1.getPhilHealthDeduction();
        double total_benefit = benefit1 + benefit2 + benefit3;
        double annualTaxDueNew = user1.getAnnualIncomeTaxNew(annualTaxableIncomeNew);
        double annualTaxDueOld = user1.getAnnualIncomeTaxOld(annualTaxableIncomeOld);
        double monthlyTaxDueNew = user1.getAnnualIncomeTaxNew(annualTaxableIncomeNew) / 12;
        double monthlyTaxDueOld = user1.getAnnualIncomeTaxOld(annualTaxableIncomeOld) / 12;
        
        // Take Home Pay returns zero when result is less than zero
        double takeHomePayNew = 0;
        double qualifierTHPNew = income - (monthlyTaxDueNew + total_benefit);
        if (qualifierTHPNew >= 0)
            takeHomePayNew = qualifierTHPNew;
        else
            takeHomePayNew = 0;
        double takeHomePayOld = 0;
        
        double qualifierTHPOld = income - (monthlyTaxDueOld + total_benefit);
        if (qualifierTHPNew >= 0)
            takeHomePayOld = qualifierTHPOld;
        else
            takeHomePayOld = 0;

        
        double taxSavings = monthlyTaxDueOld - monthlyTaxDueNew;
        
        //Converting results to String
        String displayOldATI = df.format(annualTaxableIncomeOld);
        String displayNewATI = df.format(annualTaxableIncomeNew);
        String displayOldATD = df.format(annualTaxDueOld);
        String displayNewATD = df.format(annualTaxDueNew);
        String displayOldMTD = df.format(monthlyTaxDueOld);
        String displayNewMTD = df.format(monthlyTaxDueNew);
        String displayOldTHP = df.format(takeHomePayOld);
        String displayNewTHP = df.format(takeHomePayNew);
        String displayTaxSavings = df.format(taxSavings);
        String displaySSS = df.format(benefit1);
        String displayPAGIBIG = df.format(benefit2);
        String displayPhilhealth = df.format(benefit3);
        String displayTotalBenefit = df.format(total_benefit);
        
        
        // Display in GUI Form
        this.NameDisplay.setText("WELCOME! " + user1.getName());
        this.OldATIShowDisplay.setText("P " + displayOldATI);
        this.NewATIShowDisplay.setText("P " + displayNewATI);
        this.OldATDShowDisplay.setText("P " + displayOldATD);
        this.NewATDShowDisplay.setText("P " + displayNewATD);
        this.OldMTDShowDisplay.setText("P " + displayOldMTD);
        this.NewMTDShowDisplay.setText("P " + displayNewMTD);
        this.OldTHPShowDisplay.setText("P " + displayOldTHP);
        this.NewTHPShowDisplay.setText("P " + displayNewTHP);
        this.TaxSavingsShowDisplay.setText("P " + displayTaxSavings);
        this.SSSShowDisplay.setText("P " + displaySSS);
        this.PhilHealthShowDisplay.setText("P " + displayPhilhealth);
        this.PAGIBIGShowDisplay.setText("P " + displayPAGIBIG);
        this.TotalContributionShowDisplay.setText("P " + displayTotalBenefit);
        
        } 
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Please enter needed values "
                    + "(Input number only in Monthly Income Field, (No Commas))"
                    , "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void IncomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncomeTextFieldActionPerformed

    private void SelfEmployedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelfEmployedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelfEmployedButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnnualTaxDueLabel;
    private javax.swing.JLabel AnnualTaxLabel1;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JRadioButton CivilStatusButtonNo;
    private javax.swing.JRadioButton CivilStatusButtonYes;
    private javax.swing.JLabel CivilStatusLabel;
    private javax.swing.JLabel ContributionsLabel;
    private javax.swing.JRadioButton DependentButton0;
    private javax.swing.JRadioButton DependentButton1;
    private javax.swing.JRadioButton DependentButton2;
    private javax.swing.JRadioButton DependentButton3;
    private javax.swing.JRadioButton DependentButton4;
    private javax.swing.JLabel DependentsLabel;
    private javax.swing.JRadioButton EmployedButton;
    private javax.swing.JLabel EmploymentStatusLabel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel IncomeLabel;
    private javax.swing.JTextField IncomeTextField;
    private javax.swing.JLabel MainLabel;
    private javax.swing.JLabel MonthlyTaxDueLabel;
    private javax.swing.JLabel NameDisplay;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NewATDShowDisplay;
    private javax.swing.JLabel NewATIShowDisplay;
    private javax.swing.JLabel NewMTDShowDisplay;
    private javax.swing.JLabel NewTHPShowDisplay;
    private javax.swing.JLabel OldATDShowDisplay;
    private javax.swing.JLabel OldATIShowDisplay;
    private javax.swing.JLabel OldMTDShowDisplay;
    private javax.swing.JLabel OldTHPShowDisplay;
    private javax.swing.JLabel OldTaxLabel;
    private javax.swing.JLabel PAGIBIGContributionLabel;
    private javax.swing.JLabel PAGIBIGShowDisplay;
    private javax.swing.JLabel PhilHealthContributionLabel;
    private javax.swing.JLabel PhilHealthShowDisplay;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel SSSContributionLabel;
    private javax.swing.JLabel SSSShowDisplay;
    private javax.swing.JRadioButton SelfEmployedButton;
    private javax.swing.JLabel TakeHomePayLabel;
    private javax.swing.JLabel TaxSavingsLabel;
    private javax.swing.JLabel TaxSavingsShowDisplay;
    private javax.swing.JLabel TotalContributionShowDisplay;
    private javax.swing.JLabel TotalContributionsLabel;
    private javax.swing.JLabel TrainLawLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
